package modelos;
// Generated 12/11/2017 01:00:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Long identificacion;
     private String nombre;
     private Long telefono;
     private String correo;
     private String direccion;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Cliente() {
    }

	
    public Cliente(Long identificacion, String nombre, Long telefono, String correo, String direccion) {
        this.identificacion = identificacion;
        this.nombre = nombre;
        this.telefono = telefono;
        this.correo = correo;
        this.direccion = direccion;
    }
    public Cliente(Long identificacion, String nombre, Long telefono, String correo, String direccion, Set<Prestamo> prestamos) {
       this.identificacion = identificacion;
       this.nombre = nombre;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.prestamos = prestamos;
    }
   
    public Long getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(Long identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


