package modelos;
// Generated 12/11/2017 01:00:41 PM by Hibernate Tools 4.0.0



/**
 * DetPrestamoLibroId generated by hbm2java
 */
public class DetPrestamoLibroId  implements java.io.Serializable {


     private Long idLibro;
     private String idPrestamo;
     private String fechaDevolucion;

    public DetPrestamoLibroId() {
    }

	
    public DetPrestamoLibroId(Long idLibro, String idPrestamo) {
        this.idLibro = idLibro;
        this.idPrestamo = idPrestamo;
    }
    public DetPrestamoLibroId(Long idLibro, String idPrestamo, String fechaDevolucion) {
       this.idLibro = idLibro;
       this.idPrestamo = idPrestamo;
       this.fechaDevolucion = fechaDevolucion;
    }
   
    public Long getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Long idLibro) {
        this.idLibro = idLibro;
    }
    public String getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(String idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public String getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(String fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetPrestamoLibroId) ) return false;
		 DetPrestamoLibroId castOther = ( DetPrestamoLibroId ) other; 
         
		 return ( (this.getIdLibro()==castOther.getIdLibro()) || ( this.getIdLibro()!=null && castOther.getIdLibro()!=null && this.getIdLibro().equals(castOther.getIdLibro()) ) )
 && ( (this.getIdPrestamo()==castOther.getIdPrestamo()) || ( this.getIdPrestamo()!=null && castOther.getIdPrestamo()!=null && this.getIdPrestamo().equals(castOther.getIdPrestamo()) ) )
 && ( (this.getFechaDevolucion()==castOther.getFechaDevolucion()) || ( this.getFechaDevolucion()!=null && castOther.getFechaDevolucion()!=null && this.getFechaDevolucion().equals(castOther.getFechaDevolucion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdLibro() == null ? 0 : this.getIdLibro().hashCode() );
         result = 37 * result + ( getIdPrestamo() == null ? 0 : this.getIdPrestamo().hashCode() );
         result = 37 * result + ( getFechaDevolucion() == null ? 0 : this.getFechaDevolucion().hashCode() );
         return result;
   }   


}


