package modelos;
// Generated 12/11/2017 01:00:41 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private String idPrestamo;
     private Cliente cliente;
     private Usuario usuario;
     private Date fechaPrestamo;
     private String estado;
     private Set<DetPrestamoLibro> detPrestamoLibros = new HashSet<DetPrestamoLibro>(0);

    public Prestamo() {
    }

	
    public Prestamo(String idPrestamo, Cliente cliente, Usuario usuario, Date fechaPrestamo, String estado) {
        this.idPrestamo = idPrestamo;
        this.cliente = cliente;
        this.usuario = usuario;
        this.fechaPrestamo = fechaPrestamo;
        this.estado = estado;
    }
    public Prestamo(String idPrestamo, Cliente cliente, Usuario usuario, Date fechaPrestamo, String estado, Set<DetPrestamoLibro> detPrestamoLibros) {
       this.idPrestamo = idPrestamo;
       this.cliente = cliente;
       this.usuario = usuario;
       this.fechaPrestamo = fechaPrestamo;
       this.estado = estado;
       this.detPrestamoLibros = detPrestamoLibros;
    }
   
    public String getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(String idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<DetPrestamoLibro> getDetPrestamoLibros() {
        return this.detPrestamoLibros;
    }
    
    public void setDetPrestamoLibros(Set<DetPrestamoLibro> detPrestamoLibros) {
        this.detPrestamoLibros = detPrestamoLibros;
    }




}


