package modelos;
// Generated 12/11/2017 01:00:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String nombre;
     private String identificacion;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String nombre, String identificacion) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.identificacion = identificacion;
    }
    public Usuario(String idUsuario, String nombre, String identificacion, Set<Prestamo> prestamos) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.identificacion = identificacion;
       this.prestamos = prestamos;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }




}


